import type { Grade, SessionType } from '@prisma/client'

export type SeedStudentRow = {
  firstName: string
  lastName: string
  grade: Grade
  school: string
  baselineIncidents: number
  currentMonthIncidents: number
  intakeDate: string
  tier: 'A' | 'B' | 'C' | 'D'
  presenting: string
  referredBy: string
  interventions: SessionType[]
  counselorIndex: number
}

export const STUDENTS: SeedStudentRow[] = [
  // ── TIER A: STRONG REDUCERS (25) ─────────────────────────────────────
  { firstName: 'Marcus', lastName: 'Johnson', grade: 'G7', school: 'Jefferson Middle School', baselineIncidents: 12, currentMonthIncidents: 1, intakeDate: '2024-09-05', tier: 'A', presenting: 'Frequent office referrals for disrupting class and aggressive responses to peers. History of physical altercations.', referredBy: 'Ms. Patricia Wong', interventions: ['behavioral_observation', 'emotional_regulation'], counselorIndex: 0 },
  { firstName: 'Destiny', lastName: 'Williams', grade: 'G8', school: 'Jefferson Middle School', baselineIncidents: 14, currentMonthIncidents: 2, intakeDate: '2024-09-10', tier: 'A', presenting: 'Three suspensions in first two weeks. Difficulty managing frustration. Physical confrontations with peers.', referredBy: 'Principal Davis', interventions: ['behavioral_observation', 'peer_conflict_mediation'], counselorIndex: 1 },
  { firstName: 'Jaylen', lastName: 'Carter', grade: 'G9', school: 'Tracy High School', baselineIncidents: 11, currentMonthIncidents: 1, intakeDate: '2024-09-08', tier: 'A', presenting: 'Chronic classroom disruption and defiance toward teachers. Two OSS in prior year.', referredBy: 'Mr. Robert Chen', interventions: ['classroom_support', 'emotional_regulation'], counselorIndex: 0 },
  { firstName: 'Aaliyah', lastName: 'Brown', grade: 'G7', school: 'Williams Middle School', baselineIncidents: 10, currentMonthIncidents: 1, intakeDate: '2024-09-12', tier: 'A', presenting: 'Peer conflict escalating to physical fights. Difficulty with emotional regulation in group settings.', referredBy: 'Ms. Sandra Torres', interventions: ['peer_conflict_mediation', 'group_behavior_support'], counselorIndex: 1 },
  { firstName: 'Darius', lastName: 'Thompson', grade: 'G10', school: 'Tracy High School', baselineIncidents: 13, currentMonthIncidents: 2, intakeDate: '2024-09-15', tier: 'A', presenting: 'Repeated suspensions for fighting. Significant anger management concerns. Struggling academically due to absences.', referredBy: 'Coach Williams', interventions: ['behavioral_observation', 'emotional_regulation', 'check_in'], counselorIndex: 0 },
  { firstName: 'Kayla', lastName: 'Martinez', grade: 'G8', school: 'Williams Middle School', baselineIncidents: 9, currentMonthIncidents: 1, intakeDate: '2024-09-18', tier: 'A', presenting: 'Social-emotional dysregulation. Bullying behavior toward peers. Difficulty accepting redirection from adults.', referredBy: 'Ms. Jennifer Kim', interventions: ['emotional_regulation', 'peer_conflict_mediation'], counselorIndex: 1 },
  { firstName: 'Tyrese', lastName: 'Davis', grade: 'G11', school: 'West High School', baselineIncidents: 11, currentMonthIncidents: 2, intakeDate: '2024-09-20', tier: 'A', presenting: 'Chronic tardiness and classroom walkouts. Escalating defiance. At risk of credit failure.', referredBy: 'Ms. Amanda Foster', interventions: ['check_in', 'classroom_support'], counselorIndex: 0 },
  { firstName: 'Brianna', lastName: 'Wilson', grade: 'G6', school: 'Jefferson Middle School', baselineIncidents: 8, currentMonthIncidents: 1, intakeDate: '2024-09-22', tier: 'A', presenting: 'New to middle school. Significant transition anxiety presenting as defiance and shutting down.', referredBy: 'Mr. Derek Okafor', interventions: ['emotional_regulation', 'classroom_support'], counselorIndex: 1 },
  { firstName: 'Andre', lastName: 'Robinson', grade: 'G8', school: 'Tracy High School', baselineIncidents: 10, currentMonthIncidents: 1, intakeDate: '2024-09-25', tier: 'A', presenting: 'Aggressive verbal responses to peers and staff. Two ISS first month. Home instability reported.', referredBy: 'Ms. Lisa Nguyen', interventions: ['behavioral_observation', 'emotional_regulation'], counselorIndex: 0 },
  { firstName: 'Jasmine', lastName: 'Taylor', grade: 'G9', school: 'West High School', baselineIncidents: 12, currentMonthIncidents: 2, intakeDate: '2024-10-01', tier: 'A', presenting: 'History of peer conflict and physical altercations. Strong academic ability undermined by behavioral incidents.', referredBy: 'Principal Marcus Reid', interventions: ['peer_conflict_mediation', 'behavioral_observation'], counselorIndex: 1 },
  { firstName: 'Cameron', lastName: 'Harris', grade: 'G7', school: 'Williams Middle School', baselineIncidents: 9, currentMonthIncidents: 1, intakeDate: '2024-10-05', tier: 'A', presenting: 'Classroom disruption and refusal to complete work. Peer pressure involvement in incidents.', referredBy: 'Ms. Rachel Green', interventions: ['classroom_support', 'check_in'], counselorIndex: 0 },
  { firstName: 'Monique', lastName: 'Lewis', grade: 'G11', school: 'Tracy High School', baselineIncidents: 11, currentMonthIncidents: 2, intakeDate: '2024-10-08', tier: 'A', presenting: 'Chronic truancy and defiance. Parent-school relationship conflict contributing to disengagement.', referredBy: 'Counselor Hayes', interventions: ['check_in', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Isaiah', lastName: 'Jackson', grade: 'G6', school: 'Jefferson Middle School', baselineIncidents: 10, currentMonthIncidents: 1, intakeDate: '2024-10-10', tier: 'A', presenting: 'Impulsive behavior and frequent office referrals. Difficulty transitioning between classes without incident.', referredBy: 'Mr. Thomas Bell', interventions: ['behavioral_observation', 'classroom_support'], counselorIndex: 0 },
  { firstName: 'Tanya', lastName: 'Moore', grade: 'G8', school: 'West High School', baselineIncidents: 8, currentMonthIncidents: 1, intakeDate: '2024-10-12', tier: 'A', presenting: 'Verbal aggression and disrespect toward staff. Difficulty managing transitions and unstructured time.', referredBy: 'Mr. James Parker', interventions: ['emotional_regulation', 'behavioral_observation'], counselorIndex: 1 },
  { firstName: 'Devon', lastName: 'Anderson', grade: 'G9', school: 'Williams Middle School', baselineIncidents: 13, currentMonthIncidents: 2, intakeDate: '2024-10-15', tier: 'A', presenting: 'Multiple fights this semester. Trauma history. Difficulty trusting adults in authority.', referredBy: 'Ms. Carla Washington', interventions: ['peer_conflict_mediation', 'emotional_regulation', 'behavioral_observation'], counselorIndex: 0 },
  { firstName: 'Keisha', lastName: 'White', grade: 'G7', school: 'Jefferson Middle School', baselineIncidents: 9, currentMonthIncidents: 1, intakeDate: '2024-10-18', tier: 'A', presenting: 'Peer conflict and social exclusion behaviors. Anxiety presenting as aggression in group settings.', referredBy: 'Ms. Nicole Adams', interventions: ['group_behavior_support', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Jordan', lastName: 'Thomas', grade: 'G10', school: 'Tracy High School', baselineIncidents: 12, currentMonthIncidents: 2, intakeDate: '2024-10-20', tier: 'A', presenting: 'Frequent defiance and classroom disruption. Two OSS this year. Credit recovery needed.', referredBy: 'Ms. Susan Clark', interventions: ['classroom_support', 'check_in'], counselorIndex: 0 },
  { firstName: 'Simone', lastName: 'Garcia', grade: 'G8', school: 'Williams Middle School', baselineIncidents: 8, currentMonthIncidents: 1, intakeDate: '2024-10-22', tier: 'A', presenting: 'Social difficulties and exclusionary behavior. Escalating peer conflicts in lunch and PE settings.', referredBy: 'Mr. Paul Mitchell', interventions: ['peer_conflict_mediation', 'group_behavior_support'], counselorIndex: 1 },
  { firstName: 'Xavier', lastName: 'Martinez', grade: 'G6', school: 'West High School', baselineIncidents: 10, currentMonthIncidents: 1, intakeDate: '2024-11-01', tier: 'A', presenting: 'Impulsive aggression on playground and in hallways. Difficulty with self-regulation when frustrated.', referredBy: 'Ms. Diana Powell', interventions: ['behavioral_observation', 'emotional_regulation'], counselorIndex: 0 },
  { firstName: 'Unique', lastName: 'Robinson', grade: 'G9', school: 'Tracy High School', baselineIncidents: 11, currentMonthIncidents: 2, intakeDate: '2024-11-05', tier: 'A', presenting: 'Repeated walkouts and refusal to attend class. Significant disengagement from school community.', referredBy: 'Mr. Kevin Turner', interventions: ['check_in', 'classroom_support', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Malik', lastName: 'Johnson', grade: 'G8', school: 'Jefferson Middle School', baselineIncidents: 9, currentMonthIncidents: 1, intakeDate: '2024-11-08', tier: 'A', presenting: 'Classroom disruption and peer conflict. Strong athletic ability — connection to sports used as leverage.', referredBy: 'Coach Davis', interventions: ['behavioral_observation', 'check_in'], counselorIndex: 0 },
  { firstName: 'Essence', lastName: 'Williams', grade: 'G11', school: 'West High School', baselineIncidents: 10, currentMonthIncidents: 1, intakeDate: '2024-11-10', tier: 'A', presenting: 'Social conflict and reputation-based fighting. Leadership potential channeled negatively.', referredBy: 'Ms. Faith Johnson', interventions: ['peer_conflict_mediation', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Tre', lastName: 'Davis', grade: 'G7', school: 'Williams Middle School', baselineIncidents: 8, currentMonthIncidents: 1, intakeDate: '2024-11-12', tier: 'A', presenting: 'Frequent teacher referrals for talking back and disrupting instruction. Responds well to one-on-one.', referredBy: 'Mr. Brian Scott', interventions: ['classroom_support', 'check_in'], counselorIndex: 0 },
  { firstName: 'Zaria', lastName: 'Thompson', grade: 'G8', school: 'Tracy High School', baselineIncidents: 9, currentMonthIncidents: 1, intakeDate: '2024-11-15', tier: 'A', presenting: 'Anxiety-driven conflict avoidance that escalates to physical response when cornered. Needs coping strategies.', referredBy: 'Ms. Tamara Russell', interventions: ['emotional_regulation', 'behavioral_observation'], counselorIndex: 1 },
  { firstName: 'Elijah', lastName: 'Brown', grade: 'G10', school: 'Jefferson Middle School', baselineIncidents: 12, currentMonthIncidents: 2, intakeDate: '2024-11-18', tier: 'A', presenting: 'Multiple suspensions for fighting. Strong peer influence group. Family cooperation is positive factor.', referredBy: 'Principal Jones', interventions: ['peer_conflict_mediation', 'behavioral_observation', 'group_behavior_support'], counselorIndex: 0 },

  // ── TIER B: MODERATE PROGRESS (25) ───────────────────────────────────
  { firstName: 'Dominique', lastName: 'Harris', grade: 'G8', school: 'West High School', baselineIncidents: 7, currentMonthIncidents: 3, intakeDate: '2024-09-16', tier: 'B', presenting: 'Classroom disruption and peer provocation. Making steady progress but still inconsistent.', referredBy: 'Ms. Yolanda Price', interventions: ['classroom_support', 'check_in'], counselorIndex: 1 },
  { firstName: 'Nathaniel', lastName: 'Lewis', grade: 'G7', school: 'Jefferson Middle School', baselineIncidents: 6, currentMonthIncidents: 3, intakeDate: '2024-09-19', tier: 'B', presenting: 'Disruptive in class, difficulty following directions. Progress is visible but slow.', referredBy: 'Mr. Alan Greene', interventions: ['behavioral_observation', 'classroom_support'], counselorIndex: 0 },
  { firstName: 'Shaniya', lastName: 'Moore', grade: 'G9', school: 'Williams Middle School', baselineIncidents: 8, currentMonthIncidents: 4, intakeDate: '2024-09-23', tier: 'B', presenting: 'Peer conflict and emotional dysregulation. Responding to counseling but needs continued support.', referredBy: 'Ms. Brenda Hall', interventions: ['emotional_regulation', 'peer_conflict_mediation'], counselorIndex: 1 },
  { firstName: 'Cortez', lastName: 'Anderson', grade: 'G11', school: 'Tracy High School', baselineIncidents: 7, currentMonthIncidents: 3, intakeDate: '2024-09-26', tier: 'B', presenting: 'Defiance and chronic tardiness. Improving attendance but occasional setbacks.', referredBy: 'Mr. Harvey Stone', interventions: ['check_in', 'classroom_support'], counselorIndex: 0 },
  { firstName: 'Imani', lastName: 'Jackson', grade: 'G6', school: 'West High School', baselineIncidents: 6, currentMonthIncidents: 2, intakeDate: '2024-09-30', tier: 'B', presenting: 'Transition difficulty from elementary. Social anxiety presenting as defiance. Progressing.', referredBy: 'Ms. Crystal Morgan', interventions: ['emotional_regulation', 'classroom_support'], counselorIndex: 1 },
  { firstName: 'Deonte', lastName: 'White', grade: 'G8', school: 'Jefferson Middle School', baselineIncidents: 9, currentMonthIncidents: 4, intakeDate: '2024-10-03', tier: 'B', presenting: 'Physical altercations and verbal aggression. Progress is real but fragile in unstructured settings.', referredBy: 'Mr. William Barnes', interventions: ['peer_conflict_mediation', 'behavioral_observation'], counselorIndex: 0 },
  { firstName: 'Raven', lastName: 'Garcia', grade: 'G9', school: 'Tracy High School', baselineIncidents: 7, currentMonthIncidents: 3, intakeDate: '2024-10-06', tier: 'B', presenting: 'Oppositional behavior and social conflict. Counseling relationship is strong. Needs consistency.', referredBy: 'Ms. Donna Fletcher', interventions: ['emotional_regulation', 'check_in'], counselorIndex: 1 },
  { firstName: 'Marcus', lastName: 'Williams', grade: 'G7', school: 'Williams Middle School', baselineIncidents: 5, currentMonthIncidents: 2, intakeDate: '2024-10-09', tier: 'B', presenting: 'Peer conflict and classroom disruption. Mild but persistent. Responds well to group interventions.', referredBy: 'Ms. Gloria Simmons', interventions: ['group_behavior_support', 'check_in'], counselorIndex: 0 },
  { firstName: 'Tierra', lastName: 'Thomas', grade: 'G8', school: 'West High School', baselineIncidents: 6, currentMonthIncidents: 3, intakeDate: '2024-10-13', tier: 'B', presenting: 'Disruptive in core classes. Home environment is unstable. Making progress despite challenges.', referredBy: 'Mr. Clarence Webb', interventions: ['behavioral_observation', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Quinton', lastName: 'Martinez', grade: 'G10', school: 'Tracy High School', baselineIncidents: 8, currentMonthIncidents: 4, intakeDate: '2024-10-16', tier: 'B', presenting: 'Chronic defiance and classroom conflict. Some progress in emotional management. Needs peer support.', referredBy: 'Ms. Irene Crawford', interventions: ['classroom_support', 'peer_conflict_mediation'], counselorIndex: 0 },
  { firstName: 'Alexis', lastName: 'Robinson', grade: 'G6', school: 'Jefferson Middle School', baselineIncidents: 5, currentMonthIncidents: 2, intakeDate: '2024-10-19', tier: 'B', presenting: 'Social exclusion behaviors and verbal bullying. Growth is visible. Group work helping significantly.', referredBy: 'Ms. Paula Owens', interventions: ['group_behavior_support', 'peer_conflict_mediation'], counselorIndex: 1 },
  { firstName: 'Jermaine', lastName: 'Johnson', grade: 'G9', school: 'Williams Middle School', baselineIncidents: 7, currentMonthIncidents: 3, intakeDate: '2024-10-23', tier: 'B', presenting: 'Aggressive responses under academic pressure. Progressing but needs continued support around testing periods.', referredBy: 'Mr. Louis Kim', interventions: ['emotional_regulation', 'behavioral_observation'], counselorIndex: 0 },
  { firstName: 'Nadia', lastName: 'Davis', grade: 'G8', school: 'West High School', baselineIncidents: 6, currentMonthIncidents: 3, intakeDate: '2024-10-26', tier: 'B', presenting: 'Verbal conflict with peers and walkouts. Improvement noted but not yet consistent across all settings.', referredBy: 'Ms. Felicia Hunt', interventions: ['peer_conflict_mediation', 'check_in'], counselorIndex: 1 },
  { firstName: 'Terrell', lastName: 'Harris', grade: 'G11', school: 'Tracy High School', baselineIncidents: 8, currentMonthIncidents: 4, intakeDate: '2024-11-02', tier: 'B', presenting: 'Chronic classroom conflict. On track for graduation but behavioral incidents threaten credit completion.', referredBy: 'Mr. Carl Jennings', interventions: ['classroom_support', 'check_in'], counselorIndex: 0 },
  { firstName: 'Kiara', lastName: 'Lewis', grade: 'G7', school: 'Jefferson Middle School', baselineIncidents: 5, currentMonthIncidents: 2, intakeDate: '2024-11-06', tier: 'B', presenting: 'Social conflict and friendship instability driving behavioral issues. Group counseling is making impact.', referredBy: 'Ms. Rita Chavez', interventions: ['group_behavior_support', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Kendrick', lastName: 'Moore', grade: 'G8', school: 'Williams Middle School', baselineIncidents: 7, currentMonthIncidents: 3, intakeDate: '2024-11-09', tier: 'B', presenting: 'Impulsive behavior in unstructured settings. Learning to self-monitor. Progress with structured check-ins.', referredBy: 'Mr. Oscar Reyes', interventions: ['behavioral_observation', 'check_in'], counselorIndex: 0 },
  { firstName: 'Amara', lastName: 'Anderson', grade: 'G9', school: 'Tracy High School', baselineIncidents: 6, currentMonthIncidents: 3, intakeDate: '2024-11-13', tier: 'B', presenting: 'Conflict with specific peer group. Avoiding triggering situations better but needs ongoing guidance.', referredBy: 'Ms. Veronica Diaz', interventions: ['peer_conflict_mediation', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Deshawn', lastName: 'White', grade: 'G10', school: 'West High School', baselineIncidents: 8, currentMonthIncidents: 4, intakeDate: '2024-11-16', tier: 'B', presenting: 'Repeated defiance and loss of control in high-pressure moments. Improving coping strategies.', referredBy: 'Ms. Annette Griffin', interventions: ['emotional_regulation', 'behavioral_observation'], counselorIndex: 0 },
  { firstName: 'Tiffany', lastName: 'Garcia', grade: 'G6', school: 'Jefferson Middle School', baselineIncidents: 5, currentMonthIncidents: 2, intakeDate: '2024-11-19', tier: 'B', presenting: 'Peer exclusion and social anxiety. Significant growth in self-advocacy. One-on-one sessions highly effective.', referredBy: 'Ms. Deborah Long', interventions: ['emotional_regulation', 'group_behavior_support'], counselorIndex: 1 },
  { firstName: 'Darrell', lastName: 'Thomas', grade: 'G8', school: 'Williams Middle School', baselineIncidents: 7, currentMonthIncidents: 3, intakeDate: '2024-11-22', tier: 'B', presenting: 'Classroom conflict and walkouts. Sports engagement has been positive influence. Needs consistency.', referredBy: 'Coach Brown', interventions: ['check_in', 'classroom_support'], counselorIndex: 0 },
  { firstName: 'Precious', lastName: 'Jackson', grade: 'G9', school: 'Tracy High School', baselineIncidents: 6, currentMonthIncidents: 3, intakeDate: '2024-12-02', tier: 'B', presenting: 'Emotional dysregulation and social conflict. Making steady gains. Family engagement increasing.', referredBy: 'Ms. Lorraine Pierce', interventions: ['emotional_regulation', 'peer_conflict_mediation'], counselorIndex: 1 },
  { firstName: 'Ronnie', lastName: 'Robinson', grade: 'G7', school: 'West High School', baselineIncidents: 5, currentMonthIncidents: 2, intakeDate: '2024-12-05', tier: 'B', presenting: 'Peer conflict and classroom disruption. Mild severity but consistent. Responding to structured support.', referredBy: 'Mr. Jerome Banks', interventions: ['classroom_support', 'behavioral_observation'], counselorIndex: 0 },
  { firstName: 'Latoya', lastName: 'Williams', grade: 'G8', school: 'Jefferson Middle School', baselineIncidents: 6, currentMonthIncidents: 3, intakeDate: '2024-12-09', tier: 'B', presenting: 'Verbal aggression toward staff and peers. Progress is real but reversal happens under stress.', referredBy: 'Ms. Sandra Bell', interventions: ['emotional_regulation', 'check_in'], counselorIndex: 1 },
  { firstName: 'Jalen', lastName: 'Davis', grade: 'G11', school: 'Tracy High School', baselineIncidents: 7, currentMonthIncidents: 3, intakeDate: '2024-12-12', tier: 'B', presenting: 'Chronic conflict and credit risk. College aspirations motivating engagement with behavioral support.', referredBy: 'Ms. Nancy Ford', interventions: ['check_in', 'classroom_support'], counselorIndex: 0 },
  { firstName: 'Shayla', lastName: 'Harris', grade: 'G7', school: 'Williams Middle School', baselineIncidents: 5, currentMonthIncidents: 2, intakeDate: '2024-12-16', tier: 'B', presenting: 'Social conflict and peer drama driving behavioral incidents. Group sessions producing strong results.', referredBy: 'Ms. Angela Warren', interventions: ['group_behavior_support', 'peer_conflict_mediation'], counselorIndex: 1 },

  // ── TIER C: PLATEAU (10) ─────────────────────────────────────────────
  { firstName: 'Brandon', lastName: 'Lewis', grade: 'G8', school: 'Jefferson Middle School', baselineIncidents: 8, currentMonthIncidents: 7, intakeDate: '2024-10-01', tier: 'C', presenting: 'Persistent behavioral issues with minimal change. May need plan review and approach adjustment.', referredBy: 'Mr. Tony Nash', interventions: ['behavioral_observation', 'emotional_regulation'], counselorIndex: 0 },
  { firstName: 'Ciara', lastName: 'Moore', grade: 'G9', school: 'West High School', baselineIncidents: 7, currentMonthIncidents: 6, intakeDate: '2024-10-04', tier: 'C', presenting: 'Flat progress on emotional regulation goals. Home factors limiting progress. Plan review indicated.', referredBy: 'Ms. Wanda Stephens', interventions: ['emotional_regulation', 'check_in'], counselorIndex: 1 },
  { firstName: 'Dontae', lastName: 'Anderson', grade: 'G7', school: 'Williams Middle School', baselineIncidents: 6, currentMonthIncidents: 5, intakeDate: '2024-10-07', tier: 'C', presenting: 'Inconsistent engagement with counseling. Peer group influence strong and counterproductive.', referredBy: 'Ms. Cynthia Oliver', interventions: ['peer_conflict_mediation', 'group_behavior_support'], counselorIndex: 0 },
  { firstName: 'Fatima', lastName: 'White', grade: 'G10', school: 'Tracy High School', baselineIncidents: 9, currentMonthIncidents: 8, intakeDate: '2024-10-11', tier: 'C', presenting: 'Complex trauma history. Gains are fragile and inconsistent. Licensed clinician referral being considered.', referredBy: 'Counselor Webb', interventions: ['emotional_regulation', 'behavioral_observation'], counselorIndex: 1 },
  { firstName: 'Gerald', lastName: 'Garcia', grade: 'G8', school: 'Jefferson Middle School', baselineIncidents: 7, currentMonthIncidents: 6, intakeDate: '2024-10-14', tier: 'C', presenting: 'Repeated classroom conflict. Strategy changes have not yet produced measurable improvement.', referredBy: 'Mr. Patrick Norris', interventions: ['classroom_support', 'check_in'], counselorIndex: 0 },
  { firstName: 'Heaven', lastName: 'Thomas', grade: 'G7', school: 'West High School', baselineIncidents: 6, currentMonthIncidents: 5, intakeDate: '2024-10-17', tier: 'C', presenting: 'Social conflict and exclusionary behavior. Progress plateau after initial gains. New approach being planned.', referredBy: 'Ms. Dorothy Mason', interventions: ['group_behavior_support', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Ivan', lastName: 'Johnson', grade: 'G9', school: 'Williams Middle School', baselineIncidents: 8, currentMonthIncidents: 7, intakeDate: '2024-11-03', tier: 'C', presenting: 'Defiance and conflict not responding to current intervention mix. Milestone review in progress.', referredBy: 'Mr. Howard Ellis', interventions: ['behavioral_observation', 'classroom_support'], counselorIndex: 0 },
  { firstName: 'Jada', lastName: 'Robinson', grade: 'G8', school: 'Tracy High School', baselineIncidents: 7, currentMonthIncidents: 6, intakeDate: '2024-11-07', tier: 'C', presenting: 'Emotional dysregulation plateaued. Peer relationships still volatile. Exploring new intervention strategies.', referredBy: 'Ms. Renee Carpenter', interventions: ['emotional_regulation', 'peer_conflict_mediation'], counselorIndex: 1 },
  { firstName: 'Kevin', lastName: 'Williams', grade: 'G11', school: 'West High School', baselineIncidents: 8, currentMonthIncidents: 7, intakeDate: '2024-11-11', tier: 'C', presenting: 'Chronic defiance. Some insight developing but not translating to behavior change consistently.', referredBy: 'Ms. Bonnie Watts', interventions: ['check_in', 'behavioral_observation'], counselorIndex: 0 },
  { firstName: 'Lola', lastName: 'Davis', grade: 'G6', school: 'Jefferson Middle School', baselineIncidents: 6, currentMonthIncidents: 5, intakeDate: '2024-11-14', tier: 'C', presenting: 'Transition difficulties persisting. Positive relationship with counselor but behavior change limited.', referredBy: 'Mr. Phillip Moody', interventions: ['classroom_support', 'emotional_regulation'], counselorIndex: 1 },

  // ── TIER D: REGRESSION / RECENT INTAKE (10) ──────────────────────────
  { firstName: 'Michael', lastName: 'Harris', grade: 'G8', school: 'Tracy High School', baselineIncidents: 5, currentMonthIncidents: 9, intakeDate: '2025-01-06', tier: 'D', presenting: 'Recent regression following family crisis. Previously stable student now escalating. Urgent review needed.', referredBy: 'Ms. Gloria Hines', interventions: ['emotional_regulation', 'behavioral_observation', 'check_in'], counselorIndex: 0 },
  { firstName: 'Nicole', lastName: 'Lewis', grade: 'G9', school: 'West High School', baselineIncidents: 4, currentMonthIncidents: 8, intakeDate: '2025-01-10', tier: 'D', presenting: 'New referral with acute onset. No prior counseling history. Intake assessment in progress.', referredBy: 'Principal Adams', interventions: ['behavioral_observation', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Omar', lastName: 'Moore', grade: 'G7', school: 'Jefferson Middle School', baselineIncidents: 6, currentMonthIncidents: 10, intakeDate: '2025-01-13', tier: 'D', presenting: 'Significant escalation this semester. Multiple suspensions in January. Crisis-level intervention underway.', referredBy: 'Mr. Russell Freeman', interventions: ['behavioral_observation', 'peer_conflict_mediation', 'emotional_regulation'], counselorIndex: 0 },
  { firstName: 'Patrice', lastName: 'Anderson', grade: 'G10', school: 'Williams Middle School', baselineIncidents: 5, currentMonthIncidents: 8, intakeDate: '2025-01-17', tier: 'D', presenting: 'New referral. Chronic defiance and multiple incidents in first two weeks of semester.', referredBy: 'Ms. Harriet Cole', interventions: ['classroom_support', 'behavioral_observation'], counselorIndex: 1 },
  { firstName: 'Quincy', lastName: 'White', grade: 'G8', school: 'Tracy High School', baselineIncidents: 7, currentMonthIncidents: 11, intakeDate: '2025-01-20', tier: 'D', presenting: 'Regression after winter break. Two OSS in January alone. Safety concern flagged — licensed review pending.', referredBy: 'Counselor Davis', interventions: ['emotional_regulation', 'behavioral_observation', 'check_in'], counselorIndex: 0 },
  { firstName: 'Rosa', lastName: 'Garcia', grade: 'G6', school: 'West High School', baselineIncidents: 3, currentMonthIncidents: 7, intakeDate: '2025-01-24', tier: 'D', presenting: 'New to the system. Acute onset of behavioral issues. First-generation counseling engagement. Early stage.', referredBy: 'Ms. Alma Reyes', interventions: ['behavioral_observation', 'emotional_regulation'], counselorIndex: 1 },
  { firstName: 'Stephon', lastName: 'Thomas', grade: 'G9', school: 'Jefferson Middle School', baselineIncidents: 6, currentMonthIncidents: 9, intakeDate: '2025-02-03', tier: 'D', presenting: 'Escalating incidents this year. New referral — initial assessment reveals complex home situation.', referredBy: 'Mr. Vincent Cross', interventions: ['behavioral_observation', 'emotional_regulation', 'peer_conflict_mediation'], counselorIndex: 0 },
  { firstName: 'Tamara', lastName: 'Robinson', grade: 'G7', school: 'Williams Middle School', baselineIncidents: 4, currentMonthIncidents: 7, intakeDate: '2025-02-07', tier: 'D', presenting: 'Recent intake. Teacher referrals escalating. Still building counseling relationship. Early sessions only.', referredBy: 'Ms. Judith Moon', interventions: ['behavioral_observation', 'check_in'], counselorIndex: 1 },
  { firstName: 'Uriah', lastName: 'Johnson', grade: 'G11', school: 'Tracy High School', baselineIncidents: 5, currentMonthIncidents: 8, intakeDate: '2025-02-10', tier: 'D', presenting: 'Senior year regression. College plans disrupted by escalating behavior. High stakes intervention.', referredBy: 'Ms. Grace Hammond', interventions: ['emotional_regulation', 'check_in', 'classroom_support'], counselorIndex: 0 },
  { firstName: 'Vanessa', lastName: 'Williams', grade: 'G6', school: 'West High School', baselineIncidents: 3, currentMonthIncidents: 6, intakeDate: '2025-02-14', tier: 'D', presenting: 'Most recent intake. Just started counseling. First two sessions completed. Baseline being established.', referredBy: 'Mr. Arthur Bloom', interventions: ['behavioral_observation', 'emotional_regulation'], counselorIndex: 1 },
]
export const STUDENT_COUNT = STUDENTS.length
